---
# MySQL Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rootpassword"
        - name: MYSQL_DATABASE
          value: "knowledge_acquisition"
        - name: MYSQL_USER
          value: "admin"
        - name: MYSQL_PASSWORD
          value: "Adminvijay12345"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: initdb
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: initdb
        configMap:
          name: mysql-initdb
---
# MySQL ConfigMap (for init.sql)
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb
binaryData:
  init.sql: Q1JFQVRFIFRBQkxFIElGIE5PVCBFWElTVFMgdXNlcnMgKAogICAgaWQgSU5UIEFVVE9fSU5DUkVNRU5UIFBSSU1BUlkgS0VZLAogICAgZmlyc3RfbmFtZSBWQVJDSEFSKDUwKSwKICAgIG1pZGRsZV9uYW1lIFZBUkNIQVIoNTApLAogICAgbGFzdF9uYW1lIFZBUkNIQVIoNTApLAogICAgdXNlcm5hbWUgVkFSQ0hBUig1MCkgVU5JUVVFLAogICAgcGFzc3dvcmQgVEVYVCwKICAgIGVtYWlsIFZBUkNIQVIoMTAwKQopOwoKQ1JFQVRFIFRBQkxFIElGIE5PVCBFWElTVFMgc3R1ZGVudHMgKAogICAgaWQgSU5UIEFVVE9fSU5DUkVNRU5UIFBSSU1BUlkgS0VZLAogICAgbmFtZSBWQVJDSEFSKDEwMCksCiAgICBkYXRlX29mX2pvaW5pbmcgREFURSwKICAgIGZlZXNfcGFpZCBERUNJTUFMKDEwLCAyKSwKICAgIGRlcGFydG1lbnQgVkFSQ0hBUig1MCksCiAgICB0cmFpbmVyX25hbWUgVkFSQ0hBUigxMDApLAogICAgY29tcGFueV9uYW1lIFZBUkNIQVIoMTAwKQopOwo=
    # Base64 content of init.sql will be needed here
---
# MySQL Service
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
---
# Backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: devopsbharathi/vijay-backend:<IMAGE_TAG> # Replace with your built image
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: mysql
        - name: DB_USER
          value: admin
        - name: DB_PASSWORD
          value: Adminvijay12345
        - name: DB_NAME
          value: knowledge_acquisition
---
# Backend Service
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
  - port: 5000
    targetPort: 5000
---
# Frontend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: devopsbharathi/vijay-frontend:<IMAGE_TAG>       # Assuming Nginx serving frontend
        ports:
        - containerPort: 80
---
# Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
